### ISSUE TITLE
Can't submit newer koans using Submit program

### ISSUE THREAD

**Issue by DavidWhitlock** [DavidWhitlock/PortlandStateJava#111]
When attempting to submit the koans, one of the students noticed that the `Submit` program was complaining about some of the koans:

```
** Not submitting file /Users/david/PSU/git/PortlandStateJavaSummer2015/koans/src/java7/AboutDiamondOperator.java: it does not reside in a directory named edu/pdx/cs410J/whitlock (or in one of the koans directories)
** Not submitting file /Users/david/PSU/git/PortlandStateJavaSummer2015/koans/src/java7/AboutJava7LiteralsEnhancements.java: it does not reside in a directory named edu/pdx/cs410J/whitlock (or in one of the koans directories)
** Not submitting file /Users/david/PSU/git/PortlandStateJavaSummer2015/koans/src/java7/AboutStringsInSwitch.java: it does not reside in a directory named edu/pdx/cs410J/whitlock (or in one of the koans directories)
```

**Comment by DavidWhitlock** [comment]
I'll close this issue when I get confirmation that students can submit the koans without those messages.

**Comment by DavidWhitlock** [comment]
Nope.  Not fixed yet.

```
Just gave it a try. Failed with an exception. There are two AboutEquality.java files (one in beginner and one in intermediate) and an exception is raised when trying to add the second one: 

Exception in thread "main" java.util.zip.ZipException: duplicate entry: edu/pdx/cs410J/beazley2/AboutEquality.java
        at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:233)
        at java.util.jar.JarOutputStream.putNextEntry(JarOutputStream.java:109)
        at edu.pdx.cs410J.grader.JarMaker.makeJar(JarMaker.java:52)
        at edu.pdx.cs410J.grader.Submit.makeJarFileWith(Submit.java:500)
        at edu.pdx.cs410J.grader.Submit.submit(Submit.java:264)
        at edu.pdx.cs410J.grader.Submit.main(Submit.java:696)
```

It looks like I'm replacing the package name with the student's package.  That's fine for all of the other projects, but not the koans.

**Comment by DavidWhitlock** [comment]
I'm going to keep this issue open until more koan submissions come in.

**Comment by DavidWhitlock** [comment]
Students are able to submit koans.  I think this issue is fixed.
