### ISSUE TITLE
Can't send email from Survey and Grader programs

### ISSUE THREAD

**Issue by DavidWhitlock** [DavidWhitlock/PortlandStateJava#169]
I asked @kiarasht to test out the `Survey` and `Submit` programs to make sure that they work.  Both of them failed with the following exception:

```
Exception in thread "main" javax.mail.NoSuchProviderException: smtp
        at javax.mail.Session.getService(Session.java:811)
        at javax.mail.Session.getTransport(Session.java:741)
        at javax.mail.Session.getTransport(Session.java:682)
        at javax.mail.Session.getTransport(Session.java:662)
        at javax.mail.Session.getTransport(Session.java:719)
        at javax.mail.Transport.send0(Transport.java:249)
        at javax.mail.Transport.send(Transport.java:124)
        at edu.pdx.cs410J.grader.Submit.mailTA(Submit.java:573)
        at edu.pdx.cs410J.grader.Submit.submit(Submit.java:295)
        at edu.pdx.cs410J.grader.Submit.main(Submit.java:737)
```

**Comment by DavidWhitlock** [comment]
Changes to address this issue have been merged to master and deployed to the Maven repository.
