### ISSUE TITLE
Can't send emails because of 501 5.0.0 HELO requires domain address

### ISSUE THREAD

**Issue by DavidWhitlock** [DavidWhitlock/PortlandStateJava#203]
Both the `Submit` and `Survey` programs are failing to send email because they encounter the following exception:

```
Exception in thread "main" javax.mail.MessagingException: 501 5.0.0 HELO requires domain address

	at com.sun.mail.smtp.SMTPTransport.issueCommand(SMTPTransport.java:2215)
	at com.sun.mail.smtp.SMTPTransport.helo(SMTPTransport.java:1599)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:705)
	at javax.mail.Service.connect(Service.java:366)
	at javax.mail.Service.connect(Service.java:246)
	at javax.mail.Service.connect(Service.java:195)
	at javax.mail.Transport.send0(Transport.java:254)
	at javax.mail.Transport.send(Transport.java:124)
	at edu.pdx.cs410J.grader.Submit.mailTA(Submit.java:578)
	at edu.pdx.cs410J.grader.Submit.submit(Submit.java:295)
	at edu.pdx.cs410J.grader.Submit.main(Submit.java:742)
```

**Comment by DavidWhitlock** [comment]
Changes to address this have been merged to `master` and deployed to bintray.
