### ISSUE TITLE
Submit program unable to send email

### ISSUE THREAD

**Issue by DavidWhitlock** [DavidWhitlock/PortlandStateJava#234]
While trying out the `Submit` program, I encountered this error:

```
Exception in thread "main" javax.mail.MessagingException: can't determine local email address
	at com.sun.mail.smtp.SMTPTransport.mailFrom(SMTPTransport.java:1765)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1300)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at edu.pdx.cs410J.grader.Submit.mailTA(Submit.java:578)
	at edu.pdx.cs410J.grader.Submit.submit(Submit.java:295)
	at edu.pdx.cs410J.grader.Submit.main(Submit.java:742)
```

According to this article, I need to invoke `setFrom` on the `MimeMessage` being sent.  

https://stackoverflow.com/questions/34694468/failed-messages-javax-mail-messagingexception-cant-determine-local-email-addr

I wonder why the integration tests haven't caught this.  Perhaps I need to update greenmail or something.

**Comment by DavidWhitlock** [comment]
I verified that the same behavior occurs with the `Survey` program.  This seems eerily familiar.

**Comment by DavidWhitlock** [comment]
Changes to address this issue have been merged to `master` and deployed to bintray.
