### ISSUE TITLE
Update to latest RESTEasy version

### ISSUE THREAD

**Issue by DavidWhitlock** [DavidWhitlock/PortlandStateJava#27]
While working on issue #18, I couldn't update RESTEasy to 3.0.6.Final because, when I did, I saw the following while running the integration tests.

```
Reading xml data from /Users/david/PSU/git/PortlandStateJava/web/CreditCards.xml
Mar 30, 2014 4:20:40 PM com.sun.xml.bind.v2.util.XmlFactory createParserFactory
SEVERE: null
org.xml.sax.SAXNotRecognizedException: Feature 'http://javax.xml.XMLConstants/feature/secure-processing' is not recognized.
	at org.apache.xerces.parsers.AbstractSAXParser.setFeature(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.setFeatures(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.<init>(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserFactoryImpl.newSAXParserImpl(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserFactoryImpl.setFeature(Unknown Source)
	at com.sun.xml.bind.v2.util.XmlFactory.createParserFactory(XmlFactory.java:121)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.getXMLReader(UnmarshallerImpl.java:154)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:162)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:171)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:189)
	at edu.pdx.cs410J.di.JaxbDatabase.readFile(JaxbDatabase.java:65)
	at edu.pdx.cs410J.di.CreditCardDatabase.<init>(CreditCardDatabase.java:36)
	at edu.pdx.cs410J.di.CreditCardDatabase.<init>(CreditCardDatabase.java:28)
	at edu.pdx.cs410J.di.CreditCardDatabase$$FastClassByGuice$$1eca2d68.newInstance(<generated>)
	at com.google.inject.internal.cglib.reflect.FastConstructor.newInstance(FastConstructor.java:40)
```

I think it has something to do with the version of xerces that is used for parsing the XML file that is the credit card database.  It must be using an old version that doesn't support secure parsing.

**Comment by DavidWhitlock** [comment]
Could these help? 
   * https://github.com/cobertura/cobertura/issues/105
   * https://bugzilla.redhat.com/show_bug.cgi?id=1090487

**Comment by DavidWhitlock** [comment]
I wonder if this has something to do with the fact that we're using Jetty 6.  That might include an older version of Xerces that doesn't support `secure-processing`.

**Comment by DavidWhitlock** [comment]
Changes merged to master and deployed to Maven repository.
