### ISSUE TITLE
Upgrade to JAXB 3.X

### ISSUE THREAD

**Issue by DavidWhitlock** [DavidWhitlock/PortlandStateJava#370]
I tried to upgrade jaxb-runtime to version 3.0 and I saw these runtime errors:

```
javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
	at edu.pdx.cs410J.di.BookDatabaseTest.testAddSameBook(BookDatabaseTest.java:61)
Caused by: java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory
	at edu.pdx.cs410J.di.BookDatabaseTest.testAddSameBook(BookDatabaseTest.java:61)
```

I probably need to add some new dependencies and maybe use a new `ContextFactory`.

**Comment by DavidWhitlock** [comment]
Will be available in 2022.0.0
