### ISSUE TITLE
Port 7342 already in use on GitHub CI server

### ISSUE THREAD

**Issue by DavidWhitlock** [DavidWhitlock/PortlandStateJava#429]
A couple of weeks ago, this test began failing on the GitHub CI server:

```
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.004 s <<< FAILURE! - in edu.pdx.cs410J.rmi.MovieDatabaseRmiMainTest
Error:  edu.pdx.cs410J.rmi.MovieDatabaseRmiMainTest  Time elapsed: 0.004 s  <<< ERROR!
java.rmi.server.ExportException: 
Port already in use: 7342; nested exception is: 
	java.net.BindException: Address already in use
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.listen(TCPTransport.java:356)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.exportObject(TCPTransport.java:251)
	at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.exportObject(TCPEndpoint.java:415)
	at java.rmi/sun.rmi.transport.LiveRef.exportObject(LiveRef.java:147)
	at java.rmi/sun.rmi.server.UnicastServerRef.exportObject(UnicastServerRef.java:235)
	at java.rmi/java.rmi.server.UnicastRemoteObject.exportObject(UnicastRemoteObject.java:475)
	at java.rmi/java.rmi.server.UnicastRemoteObject.exportObject(UnicastRemoteObject.java:360)
	at edu.pdx.cs410J.rmi.MovieDatabaseRmiTestCase.bindMovieDatabaseIntoRmiRegistry(MovieDatabaseRmiTestCase.java:29)
```

**Comment by DavidWhitlock** [comment]
CI builds are working again
