### ISSUE TITLE
Update findbugs when it supports Java 8

### ISSUE THREAD

**Issue by DavidWhitlock** [DavidWhitlock/PortlandStateJava#44]
Looks like findbugs doesn't work with Java 8, either.  I get this error:

```
     [java] The following errors occurred during analysis:
     [java] Jun 24, 2014 9:35:08 PM edu.umd.cs.findbugs.TextUIBugReporter reportAnalysisError
     [java] SEVERE: Unable to get XClass for java/lang/StringBuilder
     [java] java.lang.ArrayIndexOutOfBoundsException: 5747
     [java] 	at org.objectweb.asm.ClassReader.readClass(Unknown Source)
     [java] 	at org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java] 	at edu.umd.cs.findbugs.asm.FBClassReader.accept(FBClassReader.java:44)
     [java] 	at org.objectweb.asm.ClassReader.accept(Unknown Source)
```

Looks like this is a known issue: https://jira.codehaus.org/browse/MFINDBUGS-194

Until the issue is resolved, I guess I'll take findbugs out of the archetypes.

**Comment by DavidWhitlock** [comment]
FindBugs Maven plugin now lives at http://gleclaire.github.io/findbugs-maven-plugin/

**Comment by DavidWhitlock** [comment]
Changes to address this issue have been merged to the `master` branch.
